# Data
dataset: cifar_10  # mnist or cifar_10 
num_classes: 10 
batch_size: 128
shuffle: True

# Parameters
num_epochs: 50
learning_rate: 0.001
momentum: 0.5
patience: 5

# Model
model: googlenet # lenet, googlenet or resnet18 
input_channel: 3 # 1 for MNIST, 3 for CIFAR10

save_path: ./save
