# Data
dataset: voc2007  # mnist or cifar or voc2007
num_classes: 20  # 10 for mnist and cifar, 20 for voc2007
input_channel: 3 # 1 for mnist, 3 for cifar10 and voc2007 
batch_size: 128
shuffle: True

# Parameters
num_epochs: 100
learning_rate: 0.001
momentum: 0.5
patience: 5
dropout: 0.3

# Model
model: resnet50 # lenet, googlenet, resnet18 or resnet50

save_path: ./save
